baseURL = 'https://sermons.elim-church.org.uk/'
languageCode = 'en-us'
title = 'Elim Church Crawley sermons'
# enableGitInfo = true

theme = 'jb'

paginate = 12

# Footer logo and menu title config
# footer menus are further down
[params.footer.logo]
  image = "/images/logo_no_rocket.svg"
  text = "Jupiter Broadcasting"
  url = "/"
[params.footer.left]
  headline = "Get Social"
[params.footer.center]
  headline = "" # blank to temporarily "hide"
[params.footer.right]
  headline = "Get Involved"

# Allow HTML in Markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"
  preacher = "preachers"
  guest = "guests"

# Main Menu
[[Menu.Main]]
    pre = '<img src="/images/logo_no_rocket.svg" alt="Jupiter Broadcasting logo without Rocket" style="height: 2rem">'
    identifier = "home"
    url = "/"
    weight =-100

[[Menu.Main]]
    name = "Series"
    identifier = "Series"
    url = "/series/"
    weight =-90

    [[Menu.Main]]
        name = "Coder Radio"
        identifier = "coder-radio"
        url = "/series/coder-radio/"
        weight =91
        parent = "Series"

    [[Menu.Main]]
        name = "Jupiter EXTRAS"
        identifier = "jupiter-extras"
        url = "/series/jupiter-extras/"
        weight =92
        parent = "Series"

    [[Menu.Main]]
        name = "Linux Action News"
        identifier = "linux-action-news"
        url = "/series/linux-action-news/"
        weight =93
        parent = "Series"

    [[Menu.Main]]
        name = "LINUX Unplugged"
        identifier = "linux-unplugged"
        url = "/series/linux-unplugged/"
        weight =94
        parent = "Series"

    [[Menu.Main]]
        name = "Office Hours"
        identifier = "office-hours"
        url = "/series/office-hours/"
        weight =95
        parent = "Series"

    [[Menu.Main]]
        name = "Self-Hosted"
        identifier = "self-hosted"
        url = "/series/self-hosted/"
        weight =96
        parent = "Series"

[[Menu.Main]]
    name = "Preachers"
    identifier = "preachers"
    url = "/preachers/"
    weight =80

# Footer Menu (center)
[[Menu.FooterCenter]]
    name = "" # blank to temporarily "hide"
    identifier = "home"
    url = "/"
    weight =-100

# Footer Menu (right)
[[Menu.FooterRight]]
    name = "GitHub Issues"
    identifier = "ext-github"
    url = "https://github.com/elimchurchcrawley/sermons.elim-church.org.uk/issues"
    weight =-200


# Output formats

[outputFormats]
  [outputFormats.webplayer]
  mediatype ="application/json"
  baseName = "webplayer"

[outputs]
  page = ["html"]
  # page = ["json","html","webplayer"]
  # section = ["html","rss"]
  section = ["html"]
