baseURL = 'https://sermons.elim-church.org.uk/'
languageCode = 'en-us'
title = 'Elim Church Crawley sermons'
# enableGitInfo = true

theme = 'jb'

paginate = 12

# Footer logo and menu title config
# footer menus are further down
[params.footer.logo]
  image = "/images/logo_no_rocket.svg"
  text = "Jupiter Broadcasting"
  url = "/"
[params.footer.left]
  headline = "Get Social"
[params.footer.center]
  headline = "" # blank to temporarily "hide"
[params.footer.right]
  headline = "Get Involved"

# Allow HTML in Markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"
  preacher = "preacher"
  guest = "guests"

# Main Menu
[[Menu.Main]]
    pre = '<img src="/images/logo_no_rocket.svg" alt="Jupiter Broadcasting logo without Rocket" style="height: 2rem">'
    identifier = "home"
    url = "/"
    weight =-100

[[Menu.Main]]
    name = "Series"
    identifier = "series"
    url = "/series/"
    weight =-90

    [[Menu.Main]]
        name = "Coder Radio"
        identifier = "coder-radio"
        url = "/series/coder-radio/"
        weight =91
        parent = "Series"

    [[Menu.Main]]
        name = "Jupiter EXTRAS"
        identifier = "jupiter-extras"
        url = "/show/jupiter-extras/"
        weight =92
        parent = "Series"

    [[Menu.Main]]
        name = "Linux Action News"
        identifier = "linux-action-news"
        url = "/show/linux-action-news/"
        weight =93
        parent = "Series"

    [[Menu.Main]]
        name = "LINUX Unplugged"
        identifier = "linux-unplugged"
        url = "/show/linux-unplugged/"
        weight =94
        parent = "Series"

    [[Menu.Main]]
        name = "Office Hours"
        identifier = "office-hours"
        url = "/show/office-hours/"
        weight =95
        parent = "Series"

    [[Menu.Main]]
        name = "Self-Hosted"
        identifier = "self-hosted"
        url = "/show/self-hosted/"
        weight =96
        parent = "Series"

[[Menu.Main]]
    name = "Preachers"
    identifier = "preachers"
    url = "/preachers/"
    weight =80

# Footer Menu (left)
[[Menu.FooterLeft]]
    name = "PeerTube"
    identifier = "ext-peertube"
    url = "https://jupiter.tube/"
    weight = -100

[[Menu.FooterLeft]]
    name = "YouTube"
    identifier = "ext-youtube"
    url = "https://www.youtube.com/user/jupiterbroadcasting"
    weight = -90

[[Menu.FooterLeft]]
    name = "Twitter"
    identifier = "ext-twitter"
    url = "https://twitter.com/jupitersignal"
    weight = -80

[[Menu.FooterLeft]]
    name = "Facebook"
    identifier = "ext-facebook"
    url = "http://www.facebook.com/pages/Jupiter-Broadcasting/156241429615"
    weight = -70

[[Menu.FooterLeft]]
    name = "Telegram"
    identifier = "ext-telegram"
    url = "https://www.jupiterbroadcasting.com/telegram"
    weight = -60

[[Menu.FooterLeft]]
    name = "IRC"
    identifier = "ext-irc"
    url = "https://kiwiirc.com/client/irc.geekshed.net/?nick=JBLive_?&theme=cli#jupiterbroadcasting"
    weight = -50

# Footer Menu (center)
[[Menu.FooterCenter]]
    name = "" # blank to temporarily "hide"
    identifier = "home"
    url = "/"
    weight =-100

# Footer Menu (right)
[[Menu.FooterRight]]
    name = "GitHub Issues"
    identifier = "ext-github"
    url = "https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues"
    weight =-200

[[Menu.FooterRight]]
    name = "Jupiter.Tube Issues"
    identifier = "ext-github-jupitertube"
    url = "https://github.com/JupiterBroadcasting/jupiter.tube/issues"
    weight =-80

[[Menu.FooterRight]]
    name = "Matrix Issues"
    identifier = "ext-github-matrix"
    url = "https://github.com/JupiterBroadcasting/matrix/issues"
    weight =-190

# Output formats

[outputFormats]
  [outputFormats.webplayer]
  mediatype ="application/json"
  baseName = "webplayer"

[outputs]
  page = ["html"]
  # page = ["json","html","webplayer"]
  # section = ["html","rss"]
  section = ["html"]
